
```{r}
library(tidyverse)
library(showtext)
library(patchwork)
library(dplyr)
library(plyr)
library(ragg)

font_add_google("Oswald", "oswald")
font_add_google("Roboto Condensed", "roboto condensed")
font_add_google("Share Tech Mono", "techmono")

showtext_opts(dpi = 320)
showtext_auto(enable = TRUE)
```


```{r}
athletes <- read.csv('athlete_events.csv')
```



```{r}
athletes <- as.data.frame(athletes %>% dplyr::select(everything()) %>% dplyr::filter(Team == "Nigeria"))
```

```{r}
athletes <- athletes %>%
  mutate(Sex = ifelse(Sex == "F", "Women", "Men"))

####Years for the labels & breaks

####Dataset for Outliers
oldest <- athletes %>%
  group_by(Sex) %>%
  slice_max(Age, n =1) %>%
  ungroup()


youngest <- athletes %>%
  group_by(Sex) %>%
  slice_min(Age, n = 1) %>%
  ungroup()



extreme <- youngest %>%
  bind_rows(oldest) %>%
  select(Name, Age, Sex, Year, Sport, Medal, Team, Event, ID)

####Gbenga Toriola represented Nigeria in two events which made his name show up twice in the extre data frame
extreme <- extreme[-c(3), ]

arrows <- tibble(x = c(1983, 1997, 2008, 1992), y = c(8, 8, 45, 45))

arrows <- arrows %>%
  bind_cols(extreme) %>%
  mutate(text = glue::glue("{Name} - {Age} yo - {Team} - {Sport}"))

```

```{r}
years <- athletes %>% distinct(Year)
ylabels <- tibble(x = rep(1950, 5),
                  y = seq(10, 50, 10))
```




summary(athletes)


```{r colors}
palette <- c("Men" = "#03A696", "Women" = "#F25D27")
update_geom_defaults("text", list(family = "roboto condensed"))
```

```{r}
age_distribution <- athletes %>%
  ggplot() +
  geom_text(data = ylabels, aes(x, y, label = y), color = "grey70", nudge_y = 1) +
  geom_segment(data = years, aes(x = Year, xend = Year, y = 0, yend = 20), linetype = "14", color = "grey70", inherit.aes = FALSE, size = 0.3) +
  geom_jitter(aes(Year, Age, fill = Sex), width = 1.5, size = 1.7, shape = 21, stroke = 0.1, color = "black") +
  geom_point(data = arrows, aes(x = Year, y = Age, fill = Sex), size = 3.5, shape = 21, stroke = 0.3, color = "black") +
  geom_curve(data = filter(arrows, Age > 30), aes(x = x, y = y, xend = Year, yend = Age), arrow = arrow(length = unit(0.1, "cm")), curvature = 0.4, color = "white") +
  geom_curve(data = filter(arrows, Age < 20), aes(x = x, y = y, xend = Year, yend = Age), arrow = arrow(length = unit(0.1, "cm")), curvature = -0.4, color = "white") +
  geom_text(data = arrows[1,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 1, vjust = 1) +
  geom_text(data = arrows[2,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 0, vjust = 1) +
  geom_text(data = arrows[4,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 1, vjust = 0) +
  geom_text(data = arrows[3,], aes(x = x, y = y, label = str_wrap(text,33)), color = "white", hjust = 1, vjust = 0) +
  scale_fill_manual(values = palette) +
  scale_x_continuous(breaks = years$Year, limits = c(1950, 2018), expand = c(0.02, 0.02)) +
  scale_y_continuous(breaks = seq(10, 50, 10)) +
  guides(fill = FALSE) +
  theme_void() +
  theme(panel.background = element_rect(fill = "grey20", color = NA),
        panel.grid.major.y = element_line(linetype = "14", size = 0.3, color = "grey70"),
        axis.text.y = element_blank(),
        axis.text.x = element_text(angle = 90, margin = margin(-40, 10, 10, 0), color = "grey70", vjust = -0.3, size = 12, family = "roboto condensed"))
  
```

```{r}
sex_distribution <- athletes %>%
  arrange(Year) %>%
  dplyr::group_by(Sex, Year) %>%
  dplyr::summarise(total = n()) %>%
  dplyr::ungroup() %>%
  ggplot(aes(Year, total, fill = Sex)) +
  geom_col() +
  scale_fill_manual(values = palette) +
  scale_x_continuous(limits = c(1950, 2018), expand = c(0.02, 0.02)) +
  guides(fill = guide_legend(label.position = "top",
                             title.hjust = 0.5,
                             keywidth = unit(3, "line"),
                             keyheight = unit(1, "line"),
                             nrow = 1
                             )) +
  theme_void() +
  theme(panel.background = element_rect(fill = "grey20", color = NA),
        legend.position = c(0.1, 0.90),
        legend.title = element_blank(),
        legend.text = element_text(family = "oswald", face = "bold", size = 12, color = "#D8E6F2"))
```

```{r}
final <- sex_distribution / age_distribution +
  plot_layout(nrow = 2, heights = c(0.5, 2)) +
  plot_annotation(
    title = "Age & sex distribution of Nigerian athletes in the Summer Olympic Games",
    subtitle = "And a focus on the oldest and the youngest athletes for women and men.",
    theme = theme(
      plot.background = element_rect(fill = "grey20", color = NA),
      plot.title = element_text(family = "oswald", size = 18, color = "white", hjust = 0.5, face = "bold", margin = margin(10, 0, 0, 0)),
      plot.subtitle = element_text(family = "oswald", color = "white", size = 14, hjust = 0.5, margin = margin(10, 0, 15, 0)),
     
    )
  )


ggsave("nig_olympians.png", final, device = ragg::agg_png, res = 320, width = 14, height = 10, units = "in")

```
